import type { Floor, Reservation } from "./types";

export const fmtDate = (offset: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().split("T")[0];
};
export const TODAY = fmtDate(0);
const DAY2 = fmtDate(2);
const DAY3 = fmtDate(3);
const PAST1 = fmtDate(-1);
const PAST2 = fmtDate(-2);
const PAST3 = fmtDate(-3);

export const INITIAL_FLOORS: Floor[] = [
  {
    id: "f1",
    tables: [
      { id: "T1", seats: 2, shape: "rect", x: 48, y: 48, width: 72, height: 72, status: "available" },
      {
        id: "T2",
        seats: 4,
        shape: "circle",
        x: 216,
        y: 48,
        width: 144,
        height: 216,
        status: "occupied",
        revenue: 156500,
        occupiedSeats: 4,
        guestKey: "parkK",
        orderItems: [
          { itemKey: "americano", qty: 2, price: 3500 },
          { itemKey: "cafe-latte", qty: 1, price: 4000 },
          { itemKey: "flat-white", qty: 1, price: 4500 },
          { itemKey: "honey-cold-brew", qty: 1, price: 5500 },
          { itemKey: "espresso", qty: 2, price: 3000 },
          { itemKey: "cappuccino", qty: 1, price: 4500 },
          { itemKey: "mocha", qty: 1, price: 5000 },
          { itemKey: "macchiato", qty: 1, price: 4500 },
          { itemKey: "vanilla-latte", qty: 2, price: 5000 },
          { itemKey: "caramel-latte", qty: 1, price: 5000 },
          { itemKey: "hazelnut-latte", qty: 1, price: 5000 },
          { itemKey: "matcha-latte", qty: 2, price: 5500 },
          { itemKey: "chai-latte", qty: 1, price: 5000 },
          { itemKey: "hot-chocolate", qty: 1, price: 5000 },
          { itemKey: "iced-americano", qty: 3, price: 3800 },
          { itemKey: "iced-latte", qty: 2, price: 4300 },
          { itemKey: "cold-brew", qty: 1, price: 5500 },
          { itemKey: "nitro-cold-brew", qty: 1, price: 6500 },
          { itemKey: "affogato", qty: 1, price: 6500 },
          { itemKey: "espresso-con-panna", qty: 1, price: 4500 },
          { itemKey: "cortado", qty: 1, price: 4500 },
          { itemKey: "flat-black", qty: 1, price: 4000 },
          { itemKey: "lemonade", qty: 2, price: 4500 },
          { itemKey: "peach-tea", qty: 1, price: 5000 },
          { itemKey: "green-tea", qty: 1, price: 4500 },
          { itemKey: "earl-grey-tea", qty: 1, price: 4500 },
          { itemKey: "chamomile-tea", qty: 1, price: 4500 },
          { itemKey: "croissant", qty: 2, price: 4000 },
          { itemKey: "blueberry-muffin", qty: 1, price: 4500 },
          { itemKey: "tiramisu", qty: 1, price: 6500 },
        ],
      },
      {
        id: "T3",
        seats: 4,
        shape: "rect",
        x: 480,
        y: 48,
        width: 144,
        height: 144,
        status: "occupied",
        revenue: 41000,
        occupiedSeats: 3,
        guestKey: "leeS",
        orderItems: [
          { itemKey: "espresso-con-panna", qty: 1, price: 4500 },
          { itemKey: "honey-cold-brew", qty: 2, price: 5500 },
          { itemKey: "oat-cold-brew", qty: 3, price: 6500 },
          { itemKey: "espresso", qty: 1, price: 3000 },
          { itemKey: "tiramisu", qty: 1, price: 6000 },
        ],
      },
      { id: "T4", seats: 2, shape: "rect", x: 504, y: 216, width: 72, height: 72, status: "available" },
      { id: "T5", seats: 4, shape: "rect", x: 48, y: 360, width: 216, height: 72, status: "available" },
      { id: "T6", seats: 6, shape: "rect", x: 48, y: 504, width: 144, height: 72, status: "available" },
      { id: "T7", seats: 2, shape: "rect", x: 264, y: 504, width: 144, height: 72, status: "available" },
      { id: "T8", seats: 4, shape: "rect", x: 480, y: 504, width: 144, height: 72, status: "available" },
      { id: "T9", seats: 6, shape: "circle", x: 696, y: 480, width: 144, height: 144, status: "available" },
      {
        id: "T10",
        seats: 6,
        shape: "rect",
        x: 552,
        y: 336,
        width: 216,
        height: 144,
        status: "occupied",
        revenue: 17500,
        occupiedSeats: 5,
        guestKey: "choiM",
        orderItems: [
          { itemKey: "vanilla-cold-brew", qty: 2, price: 6500 },
          { itemKey: "espresso-con-panna", qty: 1, price: 4500 },
        ],
      },
      { id: "T11", seats: 4, shape: "rect", x: 48, y: 648, width: 144, height: 72, status: "available" },
    ],
  },
  {
    id: "f2",
    tables: [
      { id: "T12", seats: 2, shape: "rect", x: 72, y: 48, width: 72, height: 72, status: "available" },
      {
        id: "T13",
        seats: 4,
        shape: "rect",
        x: 264,
        y: 48,
        width: 144,
        height: 72,
        status: "reserved",
        guestKey: "jiN",
        reservationTime: "12:38",
      },
      { id: "T14", seats: 4, shape: "rect", x: 480, y: 48, width: 144, height: 72, status: "available" },
      { id: "T15", seats: 6, shape: "rect", x: 72, y: 192, width: 144, height: 144, status: "available" },
      { id: "T16", seats: 2, shape: "rect", x: 288, y: 192, width: 72, height: 72, status: "available" },
      { id: "T17", seats: 4, shape: "rect", x: 456, y: 192, width: 144, height: 72, status: "available" },
      { id: "T18", seats: 2, shape: "rect", x: 72, y: 360, width: 72, height: 72, status: "available" },
      { id: "T19", seats: 4, shape: "rect", x: 264, y: 360, width: 144, height: 72, status: "available" },
    ],
  },
];

export const SAMPLE_RESERVATIONS: Reservation[] = [
  { id: "r1", tableId: "T2", guestName: "", guestKey: "kimM", partySize: 4, startTime: "18:00", duration: 2, day: TODAY, type: "confirmed" },
  { id: "r2", tableId: "T3", guestName: "", guestKey: "parkS", partySize: 2, startTime: "19:00", duration: 1.5, day: TODAY, type: "confirmed" },
  { id: "r3", tableId: "T5", guestName: "", guestKey: "leeJ", partySize: 6, startTime: "20:00", duration: 2, day: TODAY, type: "confirmed" },
  { id: "r4", tableId: "T6", guestName: "", guestKey: "choiK", partySize: 4, startTime: "18:30", duration: 2, day: TODAY, type: "confirmed" },
  { id: "r5", tableId: "T8", guestName: "", guestKey: "jungH", partySize: 3, startTime: "21:00", duration: 1.5, day: TODAY, type: "request" },
  { id: "r6", tableId: "T1", guestName: "", guestKey: "yoonA", partySize: 2, startTime: "19:30", duration: 1, day: TODAY, type: "confirmed" },
  { id: "r7", tableId: "", guestName: "", guestKey: "yooN", partySize: 4, startTime: "17:00", duration: 1.5, day: TODAY, type: "request" },
  { id: "r8", tableId: "", guestName: "", guestKey: "hanD", partySize: 2, startTime: "18:30", duration: 1, day: TODAY, type: "request" },
  { id: "r9", tableId: "", guestName: "", guestKey: "kangN", partySize: 4, startTime: "17:30", duration: 2, day: TODAY, type: "request" },
  { id: "r10", tableId: "", guestName: "", guestKey: "shinB", partySize: 6, startTime: "19:00", duration: 2, day: TODAY, type: "request" },
  { id: "r11", tableId: "T9", guestName: "", guestKey: "songY", partySize: 4, startTime: "19:00", duration: 1.5, day: TODAY, type: "request" },
  { id: "r12", tableId: "T10", guestName: "", guestKey: "imW", partySize: 6, startTime: "17:30", duration: 2.5, day: TODAY, type: "confirmed" },
  { id: "r13", tableId: "T2", guestName: "", guestKey: "ohS", partySize: 4, startTime: "12:00", duration: 2, day: DAY2, type: "confirmed" },
  { id: "r14", tableId: "", guestName: "", guestKey: "baekJ", partySize: 8, startTime: "18:00", duration: 3, day: DAY2, type: "request" },
  { id: "r15", tableId: "T5", guestName: "", guestKey: "seoH", partySize: 2, startTime: "19:30", duration: 1.5, day: DAY2, type: "confirmed" },
  { id: "r16", tableId: "", guestName: "", guestKey: "hwangD", partySize: 4, startTime: "20:00", duration: 2, day: DAY2, type: "request" },
  { id: "r17", tableId: "T1", guestName: "", guestKey: "moonY", partySize: 2, startTime: "11:00", duration: 1, day: DAY2, type: "confirmed" },
  { id: "r18", tableId: "T3", guestName: "", guestKey: "ryuK", partySize: 6, startTime: "17:00", duration: 2.5, day: DAY3, type: "confirmed" },
  { id: "r19", tableId: "", guestName: "", guestKey: "jangM", partySize: 4, startTime: "19:00", duration: 2, day: DAY3, type: "request" },
  { id: "r20", tableId: "", guestName: "", guestKey: "kwonT", partySize: 2, startTime: "13:00", duration: 1.5, day: DAY3, type: "request" },
  { id: "r21", tableId: "T6", guestName: "", guestKey: "naE", partySize: 8, startTime: "18:30", duration: 2, day: DAY3, type: "confirmed" },
  { id: "r22", tableId: "", guestName: "", guestKey: "ahnS", partySize: 6, startTime: "20:30", duration: 2, day: DAY3, type: "request" },
  { id: "p1", tableId: "T2", guestName: "", guestKey: "choW", partySize: 4, startTime: "12:00", duration: 2, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p2", tableId: "T5", guestName: "", guestKey: "baeR", partySize: 2, startTime: "13:30", duration: 1, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p3", tableId: "T6", guestName: "", guestKey: "kimE", partySize: 6, startTime: "18:00", duration: 2.5, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true, extensionCount: 1 },
  { id: "p4", tableId: "T3", guestName: "", guestKey: "limS", partySize: 4, startTime: "19:00", duration: 2, day: PAST1, type: "confirmed", status: "NO_SHOW" },
  { id: "p5", tableId: "T8", guestName: "", guestKey: "parkJ", partySize: 3, startTime: "20:00", duration: 1.5, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p6", tableId: "T1", guestName: "", guestKey: "goH", partySize: 2, startTime: "21:00", duration: 1, day: PAST1, type: "confirmed", status: "NO_SHOW" },
  { id: "p4w", tableId: "T3", guestName: "", guestKey: "walkIn", partySize: 3, startTime: "19:20", duration: 1.5, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true, walkIn: true },
  { id: "p6w", tableId: "T1", guestName: "", guestKey: "walkIn", partySize: 2, startTime: "21:20", duration: 1, day: PAST1, type: "confirmed", status: "COMPLETED", paid: true, walkIn: true },
  { id: "p7", tableId: "T2", guestName: "", guestKey: "seongL", partySize: 4, startTime: "11:30", duration: 2, day: PAST2, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p8", tableId: "T9", guestName: "", guestKey: "jeonY", partySize: 6, startTime: "13:00", duration: 2.5, day: PAST2, type: "confirmed", status: "COMPLETED", paid: true, extensionCount: 2 },
  { id: "p9", tableId: "T5", guestName: "", guestKey: "nohK", partySize: 4, startTime: "18:30", duration: 2, day: PAST2, type: "confirmed", status: "NO_SHOW" },
  { id: "p9w", tableId: "T5", guestName: "", guestKey: "walkIn", partySize: 4, startTime: "18:50", duration: 1.5, day: PAST2, type: "confirmed", status: "COMPLETED", paid: true, walkIn: true },
  { id: "p10", tableId: "T10", guestName: "", guestKey: "haD", partySize: 6, startTime: "19:30", duration: 2.5, day: PAST2, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p11", tableId: "T1", guestName: "", guestKey: "minC", partySize: 2, startTime: "21:00", duration: 1, day: PAST2, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p12", tableId: "T3", guestName: "", guestKey: "kooB", partySize: 4, startTime: "12:00", duration: 2, day: PAST3, type: "confirmed", status: "COMPLETED", paid: true },
  { id: "p13", tableId: "T6", guestName: "", guestKey: "yooM", partySize: 6, startTime: "17:30", duration: 2.5, day: PAST3, type: "confirmed", status: "NO_SHOW" },
  { id: "p13w", tableId: "T6", guestName: "", guestKey: "walkIn", partySize: 5, startTime: "17:50", duration: 2, day: PAST3, type: "confirmed", status: "COMPLETED", paid: true, walkIn: true },
  { id: "p14", tableId: "T8", guestName: "", guestKey: "sunR", partySize: 3, startTime: "19:00", duration: 1.5, day: PAST3, type: "confirmed", status: "COMPLETED", paid: true, extensionCount: 1 },
  { id: "p15", tableId: "T2", guestName: "", guestKey: "ohD", partySize: 4, startTime: "20:00", duration: 2, day: PAST3, type: "confirmed", status: "COMPLETED", paid: true },
];
